import type { Metadata } from "next";
import { Geist, Geist_Mono, Overpass } from "next/font/google";
import "./globals.css";
import NavbarNasa from "@/components/navbar";

const overpassSans = Overpass({
    variable: "--font-overpass-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${overpassSans.variable} ${geistMono.variable} antialiased dark`}
            >
                <NavbarNasa />
                <div className="bg-black/60 h-screen pt-16">{children}</div>
            </body>
        </html>
    );
}
